---
title: "R Notebook"
output: md_document
---

https://www.cultureofinsight.com/blog/2018/05/02/2018-04-08-multivariate-dot-density-maps-in-r-with-sf-ggplot2/

Load the libraries
```{r, message=FALSE, warning=FALSE}
library(tidyverse) # dev version of ggplot2 required devtools::install_github('hadley/ggplot2')
library(sf)
library(lwgeom)
library(geofacet)
library(ggrepel)
```

Load the data
```{r, message=FALSE, warning=FALSE}
# election results filtered to London region
ge_data <- read_csv("http://researchbriefings.files.parliament.uk/documents/CBP-7979/HoC-GE2017-constituency-results.csv") %>% 
  filter(region_name == "London") %>% 
  select(ons_id, constituency_name, first_party, Con = con, Lab = lab, LD = ld, UKIP = ukip, Green = green)

# shapefile filtered to London region
# data available here: https://www.dropbox.com/s/4iajcx25grpx5qi/uk_650_wpc_2017_full_res_v1.8.zip?dl=0
uk <- st_read("uk_650_wpc_2017_full_res_v1.8/uk_650_wpc_2017_full_res_v1.8.shp", stringsAsFactors = FALSE, quiet = TRUE) %>% 
  st_transform(4326) %>% 
  filter(REGN == "London") %>% 
  select(ons_id = PCONCODE)

# merge the data
sf_data <- left_join(ge_data, uk) %>% 
  st_as_sf() # I'm losing sf class after join so make sf object again
```

```{r}
head(sf_data)
```

```{r, message=FALSE, warning=FALSE}
# data frame of number of dots to plot for each party (1 for every 100 votes)
num_dots <- ceiling(select(as.data.frame(sf_data), Con:Green) / 100)

# generates data frame with coordinates for each point + what party it is assiciated with
sf_dots <- map_df(names(num_dots), 
                  ~ st_sample(sf_data, size = num_dots[,.x], type = "random") %>% # generate the points in each polygon
                    st_cast("POINT") %>%                                          # cast the geom set as 'POINT' data
                    st_coordinates() %>%                                          # pull out coordinates into a matrix
                    as_tibble() %>%                                               # convert to tibble
                    setNames(c("lon","lat")) %>%                                  # set column names
                    mutate(Party = factor(.x, levels = names((num_dots))))        # add categorical party variable
                  ) # map_df then binds each party's tibble into one
```

```{r}
head(sf_dots)
tail(sf_dots)
```

Plot it
```{r}
# colour palette for our party points
pal <- c("Con" = "#0087DC", "Lab" = "#DC241F", "LD" = "#FCBB30", "UKIP" = "#70147A", "Green" = "#78B943")

ggplot() +
  geom_sf(data = sf_data, fill = "transparent",colour = "white") +
  geom_point(data = sf_dots, aes(lon, lat, colour = Party)) +
  scale_colour_manual(values = pal) +
  coord_sf(crs = 4326, datum = NA) +
  theme_void(base_family = "Helvetica Neue", base_size = 48) +
  labs(x = NULL, y = NULL,
       title = "UK General Election 2017\n",
       subtitle = "London Constituencies\n1 dot = 100 votes",
       caption = "Map by Culture of Insight @PaulCampbell91 | Data Sources: House of Commons Library, Alasdair Rae") +
  guides(colour = guide_legend(override.aes = list(size = 18))) +
  theme(legend.position = c(0.82, 1.03), legend.direction = "horizontal",
        plot.background = element_rect(fill = "#212121", color = NA), 
        panel.background = element_rect(fill = "#212121", color = NA),
        legend.background = element_rect(fill = "#212121", color = NA),
        legend.key = element_rect(fill = "#212121", colour = NA),
        plot.margin = margin(1, 1, 1, 1, "cm"),
        text =  element_text(color = "white"),
        title =  element_text(color = "white"),
        plot.title = element_text(hjust = 0.5),
        plot.caption = element_text(size = 32)
  )
ggsave("party_points2.png", dpi = 320, width = 80, height = 70, units = "cm")
```


```{r}
ggplot() +
  geom_sf(data = sf_data, aes(fill = first_party), colour = "white") +
  scale_fill_manual(values = pal, name = "Seat Winner") +
  coord_sf(crs = 4326, datum = NA) +
  theme_void() +
  theme(legend.position = c(0.8, 0.9), legend.direction = "horizontal")
```

```{r}
ggplot() +
  geom_sf(data = sf_data, fill = "white", colour = "white") +
  geom_point(data = sf_dots, aes(lon, lat, colour = Party), size=0.000000001) +
  scale_colour_manual(values = pal) +
  coord_sf(crs = 4326, datum = NA)
```

```{r}
ggplot() +
  geom_sf(data = sf_data, fill = "white", colour = "white") +
  geom_point(data = sf_dots, aes(lon, lat, colour = Party), size=0.000000001) +
  geom_sf(data = sf_data, color = "black", alpha = 0) +
  scale_colour_manual(values = pal) +
  coord_sf(crs = 4326, datum = NA)
```


```{r}
ggplot() +
  geom_sf(data = sf_data, fill = "white", colour = "grey") +
  coord_sf(crs = 4326, datum = NA)
```

```{r}
ggplot() +
  geom_sf(data = sf_data, fill = "white", colour = "transparent") +
  coord_sf(crs = 4326, datum = NA)
```

```{r}
ge_data3 <- ge_data %>%
  mutate("Total" = Con + Lab + LD + UKIP + Green)

ge_data3$geometry <- sf_data$geometry %>%
  sf::st_centroid() %>%
  as.data.frame()

ggplot() +
  geom_sf(data = sf_data, fill = "white", colour = "grey") +
  geom_sf(data = ge_data3$geometry, aes(size = ge_data3$Total)) +
  coord_sf(crs = 4326, datum = NA)

ggplot() +
  geom_sf(data = sf_data, fill = "white", colour = "grey") +
  coord_sf(crs = 4326, datum = NA)
```

```{r}
ge_data2 <- ge_data %>%
  select(-first_party) %>%
  gather(key = Party, value = Votes,
       Con, Lab, LD, UKIP, Green)
```


```{r}
#pal <- c("blue", "green", "red", "yellow", "purple")
#names(pal) <- c("Con", "Green", "Lab", "LD", "UKIP")
pal <- c("Con" = "#0087DC", "Lab" = "#DC241F", "LD" = "#FCBB30", "UKIP" = "#70147A", "Green" = "#78B943")
```

```{r}
 ge_data2 %>%
  filter(constituency_name == "Chipping Barnet") %>%
ggplot() +
  geom_point(aes(x= Party, y = constituency_name, size=Votes, colour = Party)) +
  scale_colour_manual(values= pal) +
  theme(panel.background = element_blank(), 
        legend.position="none", 
        title=element_blank())
```

```{r}
 ge_data2 %>%
  filter(constituency_name == "Chipping Barnet") %>%
ggplot() +
  geom_point(aes(x= Party, y = constituency_name, size=Votes, colour = Party)) +
  scale_colour_manual(values= pal) +
  theme(panel.background = element_blank(), 
        legend.position="none", 
        title=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

 ge_data2 %>%
  filter(constituency_name == "Chipping Barnet") %>%
ggplot() +
  geom_point(aes(x= reorder(Party, -Votes), y = constituency_name, size=Votes, colour = Party)) +
  scale_colour_manual(values= pal) +
  theme(panel.background = element_blank(), 
        legend.position="none", 
        title=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
ge_data2 %>%
ggplot() + 
  geom_point(aes(x= Party, y = constituency_name, size=Votes, colour = Party)) +
  scale_colour_manual(values= pal) +
  theme(panel.background = element_blank(), 
        legend.position="none", 
        title=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  facet_wrap(~ constituency_name)
```

Create a geofacet grid
http://john-joseph-horton.com/extending-geofacet-to-algorithmically-generate-grids-from-lat-long-data/
```{r}
#geofacet::grid_design(sf_data)
```

```{r}
centroid <- sf_data$geometry %>%
  sf::st_centroid()  %>%
  sf::st_coordinates() %>%
  as.data.frame() %>%
  rename("longitude" = X, "latitude" = Y)

centroid$rank <- 1:nrow(centroid)
centroid$city <- ge_data$constituency_name

x <- centroid$longitude
y <- centroid$latitude
index <- as.integer(centroid$rank)
city <- centroid$city

# illustrate putting on n x n grid 
row <- rank(y)
col <- rank(x)
df <- data.frame(x,y,row,col,index, city)

# grid a reduced grid 
df <- create_new_grid(x,y,city, num.iterations = 500)
```

```{r}
# raw coordinates 
ggplot(data = df, aes(x = x,y = y)) + 
  geom_text_repel(aes(label = city)) + 
  theme_bw()

# on n x n grid  
ggplot(data = df, aes(x = col,y = row)) + 
  geom_tile(fill="grey", colour = "black") + 
  geom_text_repel(aes(label = city)) +  
  theme_bw()

# plus results 
ggplot(data = df, aes(x = new.col,y = new.row)) + 
  geom_point() + 
  geom_tile(fill="grey", colour = "black") + 
  geom_text_repel(aes(label = unit.name), size = 2) + 
  theme_bw()
```

```{r}
rm(row, col, x, y, index, city, centroid)

grid <- df %>%
  select(-c(row, col, x, y)) %>%
  rename("row" = new.row, "col" = new.col, "name" = unit.name, "code" = index)
```

```{r}
ge_data2 %>%
ggplot() + 
  geom_point(aes(x= Party, y = constituency_name, size=Votes, colour = Party)) +
  scale_colour_manual(values= pal) +
  theme(panel.background = element_blank(), 
        legend.position="none", 
        title=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  facet_geo(~ constituency_name, grid = grid)
```